version: '2'
services:
    bibliotheque-app:
        image: bibliotheque
            - bibliotheque-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/bibliotheque
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bibliotheque-mariadb:
        extends:
            file: mariadb.yml
            service: bibliotheque-mariadb
